spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/discord_time_checker
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

discord:
  bot-token: ${DISCORD_BOT_TOKEN:}
  study-voice-channel-id: ${STUDY_VOICE_CHANNEL_ID:0}
  notify-channel-id: ${NOTIFY_TEXT_CHANNEL_ID:0}
  grace-period-minutes: 3
  attendance-threshold-minutes: 60
  weekly-required-days: 3
  max-warnings-before-kick: 3
